name: cme_analysis_2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyimagej
  - openjdk=11
  - cellpose
  - scikit-image
  - roifile
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-czi